spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/account_db
    username: ccuser
    password: ccpass

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
