spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/auth_db
    username: ccuser
    password: ccpass

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

security:
  jwt:
    secret: change-me-change-me-change-me-123456
    issuer: cc-platform
    expiration-seconds: 3600
