server:
  port: 8084

spring:
  application:
    name: saga-service

  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    url: jdbc:postgresql://localhost:5433/saga_db
    username: ccuser
    password: ccpass

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000

  main:
    web-application-type: servlet

# ============================
# Downstream services (LB)
# ============================
services:
  account:
    baseUrl: lb://account-service
  transaction:
    baseUrl: lb://transaction-service

# ============================
# Eureka
# ============================
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info
