server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/ccdb
    username: ccuser
    password: ccpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true

  data:
    redis:
      host: redis
      port: 6379

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info

aws:
  region: ap-northeast-1
  s3:
    bucket: cc-platform-bucket
    endpoint: http://localstack:4566
    accessKey: test
    secretKey: test

export:
  maxRows: 50000
  pageSize: 1000
